test_file: './Datasets/data/coco_test.json'
image_root: './Datasets/MSCOCO/test2014/val2014/'

bert_config: 'configs/config_bert.json'
bert_config1: 'configs/config_bert1.json'

image_res: 384
batch_size_train: 32
batch_size_test: 16

queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

epsilon: 12
num_iters: 100
constraint: 'Linf'

alpha: 0.4
distill: False
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







